name: Events Demo 1
on: 
  pull_request:
    types:
      - opened
    branches:
      - main #main FILTER TO TARGET only MAIN BRANCH
      - 'dev-*' #dev-1, dev-feature, dev-fix
      - 'feat-**' #feat-new, feat-awesome, feat-123 
  workflow_dispatch:
  push:
    branches:
      - main #main
      - 'dev-*' #dev-1, dev-feature, dev-fix
      - 'feat-**' #feat-new, feat-awesome, feat-123
    paths-ignore: # ignore changes to these paths - so that push to these paths do not trigger the workflow
      - 'docs/**'
      - '.github/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."